# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarouselImageView的封装--Jialins' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CarouselImageView的封装--Jialins
  pod ‘SDWebImage’
end
